audio/urls.py
from django.urls import path 
from .import views 

app_name = 'audio'

urlpatterns = [
    path('changespeed/', views.change_audio_speed, name='change-speed'),
    path('download-audio/', views.download_audio, name='download-audio'), 
]

image/urls.py
from django.urls import path
from .import views 

app_name = 'image'

urlpatterns = [
    path('changesize/', views.changesize, name='changesize'),
    path('bulk-change-size/', views.bulk_size_change, name='bulk-change-size'),
]

pages/urls.py
from django.urls import path 
from . import views 
import pages 

app_name = 'pages' 

urlpatterns = [
    path('', views.index, name='index'), 
    path('check/', views.check_plan, name='check'), 
    path('contact/', views.contact_form, name='contact') 
]

pay/urls.py
from django.urls import path
from .views import plan_details , plans, create_subscription, videos_limit_end
from django.conf import settings
from django.conf.urls.static import static

app_name = "pay"




urlpatterns = [
    path("plans/", plans, name="plans"),
    path("plan_detalis/<int:id>", plan_details, name="plan_detalis"),
    path("create_subscription/", create_subscription, name='create-subscription'),
    path('limit_ended/', videos_limit_end, name='video_limit_end'), 
]

project/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static




urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('accounts/', include('users.urls', namespace='accounts')),
    path('', include('pages.urls', namespace='pages')),
    path('video/', include('video.urls',namespace='video')), 
    path('image/', include('image.urls', namespace='image')),
    path('audio/', include('audio.urls', namespace='audio')),
    path('pay/', include('pay.urls', namespace='pay')),
    path('video-v2/', include('video_v2.urls', namespace='video-v2')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)


handler404 = "pages.views.handler404"
handler500 = "pages.views.handler500"

video/urls.py
from django.urls import path
from .views import *

app_name = 'video' 

urlpatterns = [
    path('', all, name='all'), 
    # path('upload/', upload, name='upload'),
    # path('create/', create_project, name='create_project'),
    # path('project/<int:id>/', project, name='project'), 
    # path('del/<int:id>/', del_img, name='del-img'),
    # path('details/<int:id>/', test_function, name='test-function'),
    path('createvideo/', combine_images, name='combine-images'),
    path('createvideowithlogo/', combine_video_withlogo, name='combine-images-withlogo'),
    path('remove_audio/', remove_audio, name='remove-audio'),
    path('changespeed/', change_speed, name='change-speed'),
    path('create_feedback_video/', feedback_video_template, name='feedback_video_template') ,
]

pages/templates/pages/contact.html
{% extends 'base.html' %}

{% block title %}
تواصل معنا
{% endblock title %}


{% block content %}

    <div>
        <h1>تواصل معنا</h1>
    </div>

    <form method="POST">

        {% csrf_token %}

        <div class="mb-3">
            <label for="InputEmail1" class="form-label">البريد الإلكتروني</label>
            <input type="email" name="email" class="form-control" id="InputEmail1" aria-describedby="emailHelp">
            <div id="emailHelp" class="form-text">أدخل البريد الإلكتروني المسجل في الموقع</div>
        </div>

        <div class="mb-3">
            <label for="Select" class="form-label">اختر الباقة</label>
            <select id="Select" class="form-select" name="plan" required>
                {% for plan in plans %}
                    <option>{{plan}}</option>
                {% endfor %}
            </select>
        </div>

        <div class="mb-3">
            <label for="details" class="form-label" >تفاصيل</label>
            <textarea id="details" class="form-control" name="details" required></textarea>
        </div>
      

        <button type="submit" class="btn btn-primary">طلب تفعيل</button>
    </form>

{% endblock content %}

pages/templates/pages/contact_completed.html
{% extends 'base.html' %}

{% block title %}
تم إرسال الرسالة
{% endblock %}

{% block content %}

<style>
    .container {
        height: calc(100vh - 100px); 
        display: flex;
        justify-content: center;
        align-items: center;
    }
</style>

<center>
    <h1>
        تم إرسال رسالتك وسيتم التواصل معك قريباً
    </h1>
    <a href="{% url 'pages:index' %}" class="btn btn-dark">العودة للصفحة الرئيسية</a>
</center>

{% endblock content %}

pages/templates/pages/index.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
الصفحة الرئيسية
{% endblock title %}


{% block content %}

<div class="container">
    <div class="row">
      <div class="col-lg-3 col-md-6 mb-4">
        <div class="card">
          <img src="{% static 'images/Artboard 1.png' %}" class="card-img-top" alt="...">
          <div class="card-body">
            <!-- <h5 class="card-title">إنشاء إعلان</h5> -->
            <!-- <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p> -->
            <a href="{% url 'video-v2:new-create' %}" class="btn text-light form-control" style="background: #ed1c24">دمج صور وفيديوهات</a>
          </div>
        </div>
      </div>

      <div class="col-lg-3 col-md-6 mb-4">
        <div class="card">
          <img src="{% static 'images/create-ad.png' %}" class="card-img-top" alt="...">
          <div class="card-body">
            <!-- <h5 class="card-title">إنشاء إعلان من صور</h5> -->
            <!-- <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p> -->
            <a href="{% url 'video:combine-images' %}" class="btn text-light form-control" style="background: #ed1c24">
              إنشاء إعلان بالصور
            </a>
          </div>
        </div>
      </div>
      <div class="col-lg-3 col-md-6 mb-4">
        <div class="card">
          <img src="{% static 'images/Artboard 1.png' %}" class="card-img-top" alt="...">
          <div class="card-body">
            <!-- <h5 class="card-title">إنشاء فيديو مع لوجو</h5> -->
            <!-- <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p> -->
            <a href="{% url 'video:combine-images-withlogo' %}" class="btn text-light form-control" style="background: #ed1c24">إنشاء فيديو مع لوجو</a>
          </div>
        </div>
      </div>


      <div class="col-lg-3 col-md-6 mb-4">
        <div class="card">
          <img src="{% static 'images/Artboard 1.png' %}" class="card-img-top" alt="...">
          <div class="card-body">
            <!-- <h5 class="card-title">إنشاء فيديو نموذج تقييم</h5> -->
            <!-- <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p> -->
            <a href="{% url 'video:feedback_video_template' %}" class="btn text-light form-control" style="background: #ed1c24">إنشاء فيديو نموذج تقييم</a>
          </div>
        </div>
      </div>

      <div class="col-lg-3 col-md-6 mb-4">
        <div class="card">
          <img src="{% static 'images/change-img-size.png' %}" class="card-img-top" alt="...">
          <div class="card-body">
            <!-- <h5 class="card-title">تغيير حجم الصورة</h5> -->
            <!-- <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p> -->
            <a href="{% url 'image:changesize' %}" class="btn text-light form-control"style="background: #ed1c24">تغيير حجم الصور</a>
          </div>
        </div>
      </div>


      <div class="col-lg-3 col-md-6 mb-4">
        <div class="card">
          <img src="{% static 'images/remove-audio.png' %}" class="card-img-top" alt="...">
          <div class="card-body">
            <!-- <h5 class="card-title">إزالة الصوت من الفيديو</h5> -->
            <!-- <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p> -->
            <a href="{% url 'video:remove-audio' %}" class="btn text-light form-control" style="background: #ed1c24">إزالة الصوت من الفيديو</a>
          </div>
        </div>
      </div>
      <div class="col-lg-3 col-md-6 mb-4">
        <div class="card">
          <img src="{% static 'images/change-video-speed.png' %}" class="card-img-top" alt="...">
          <div class="card-body">
            <!-- <h5 class="card-title">تغيير سرعة الفيديو</h5> -->
            <!-- <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p> -->
            <a href="{% url 'video:change-speed' %}" class="btn text-light form-control" style="background: #ed1c24">تغيير سرعة الفيديو</a>
          </div>
        </div>
      </div>

      <div class="col-lg-3 col-md-6 mb-4">
        <div class="card">
          <img src="{% static 'images/change-audio-speed.png' %}" class="card-img-top" alt="...">
          <div class="card-body">
            <!-- <h5 class="card-title">تغيير سرعة الصوت</h5> -->
            <!-- <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p> -->
            <a href="{% url 'audio:change-speed' %}" class="btn text-light form-control" style="background: #ed1c24">تغيير سرعة الصوت</a>
          </div>
        </div>
      </div>

      <div class="col-lg-3 col-md-6 mb-4">
        <div class="card">
          <img src="{% static 'images/Artboard 7.png' %}" class="card-img-top" alt="...">
          <div class="card-body">
            <!-- <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p> -->
            <a href="{% url 'audio:download-audio' %}" class="btn text-light form-control" style="background: #ed1c24">تحويل الفيديو إلى صوت</a>
          </div>
        </div>
      </div>

      <!-- Repeat the above HTML for each set of 4 cards -->
    </div>
  </div>

{% endblock content %}