pages/urls.py
from django.urls import path 
from . import views 
import pages 

app_name = 'pages' 

urlpatterns = [
    path('', views.index, name='index'), 
    path('check/', views.check_plan, name='check'), 
    path('contact/', views.contact_form, name='contact') 
]

pay/urls.py
from django.urls import path
from .views import plan_details , plans, create_subscription, videos_limit_end
from django.conf import settings
from django.conf.urls.static import static

app_name = "pay"




urlpatterns = [
    path("plans/", plans, name="plans"),
    path("plan_detalis/<int:id>", plan_details, name="plan_detalis"),
    path("create_subscription/", create_subscription, name='create-subscription'),
    path('limit_ended/', videos_limit_end, name='video_limit_end'), 
]

project/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static




urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('accounts/', include('users.urls', namespace='accounts')),
    path('', include('pages.urls', namespace='pages')),
    path('video/', include('video.urls',namespace='video')), 
    path('image/', include('image.urls', namespace='image')),
    path('audio/', include('audio.urls', namespace='audio')),
    path('pay/', include('pay.urls', namespace='pay')),
    path('video-v2/', include('video_v2.urls', namespace='video-v2')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)


handler404 = "pages.views.handler404"
handler500 = "pages.views.handler500"

users/urls.py
from django.urls import path
from .views import *

app_name = 'users'

urlpatterns = [
    path('profile/', profile, name='profile'),
]

video/urls.py
from django.urls import path
from .views import *

app_name = 'video' 

urlpatterns = [
    path('', all, name='all'), 
    # path('upload/', upload, name='upload'),
    # path('create/', create_project, name='create_project'),
    # path('project/<int:id>/', project, name='project'), 
    # path('del/<int:id>/', del_img, name='del-img'),
    # path('details/<int:id>/', test_function, name='test-function'),
    path('createvideo/', combine_images, name='combine-images'),
    path('createvideowithlogo/', combine_video_withlogo, name='combine-images-withlogo'),
    path('remove_audio/', remove_audio, name='remove-audio'),
    path('changespeed/', change_speed, name='change-speed'),
    path('create_feedback_video/', feedback_video_template, name='feedback_video_template') ,
]

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="ar" dir="rtl">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}{% endblock title %}</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css" integrity="sha512-iecdLmaskl7CVkqkXNQ/ZH/XLlvWZOJyj7Yy7tcenmpD1ypASozpmT/E0iPtmFIB46ZmdtAc9eNBvH0H/ZpiBw==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous">
    <!-- <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.rtl.min.css" integrity="sha384-gXt9imSW0VcJVHezoNQsP+TNrjYXoGcrqBZJpry9zJt8PCQjobwmhMGaDHTASo9N" crossorigin="anonymous"> -->
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Cairo:wght@200;300;400;500;600;700;800;900;1000&display=swap" rel="stylesheet">
    <style>
      * {
        font-family: 'Cairo', sans-serif;
      }
    </style>

    {% block stylesheet %}
    {% endblock stylesheet %}
</head>
<body>
  
  <nav class="navbar navbar-expand-lg bg-body-tertiary">
    <div class="container-fluid">
      <a class="navbar-brand" href="{% url 'pages:index' %}">
        <img src="{% static 'images/logo.png' %}" width="100" class="d-inline-block align-top" alt="Your Logo">
      </a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
          <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="{% url 'pages:index' %}">الصفحة الرئيسية</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'pay:plans' %}">الأسعار</a>
          </li>
          {% if not user.is_authenticated %}
          <li class="nav-item">
            <a href="{% url 'account_login' %}" class="nav-link">تسجيل دخول</a>
          </li>
          {% else %}
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
              حسابي
            </a>
            <ul class="dropdown-menu">
              <li><a class="dropdown-item" href="{% url 'accounts:profile' %}">الملف الشخصي</a></li>
              <li><a class="dropdown-item" href="#">Another action</a></li>
              <li><hr class="dropdown-divider"></li>
              <li><a class="dropdown-item" href="{% url 'account_logout' %}">تسجيل خروج</a></li>
            </ul>
          </li>
          {% endif %}

          <li class="nav-item">
            <a class="nav-link btn btn-sm text-light " style="background-color: #ed1c24;" href="{% url 'video:combine-images' %}">إنشاء فيديو</a>
          </li>

        </ul>
        <!-- <form class="d-flex" role="search">
          <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
          <button class="btn btn-primary" type="submit">Search</button>
        </form> -->
      </div>
    </div>
  </nav>



      <div class="container mt-3 mb-3">
        {% block content %}
        
        {% endblock content %}
      </div>

      <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.6/dist/umd/popper.min.js" integrity="sha384-oBqDVmMz9ATKxIep9tiCxS/Z9fNfEXiDAYTujMAeBAsjFuCZSmKbSSUnQlmh/jp3" crossorigin="anonymous"></script>
      <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.min.js" integrity="sha384-mQ93GR66B00ZXjt0YO5KlohRA5SY2XofN4zfuZxLkoj1gXtW8ANNCe9d5Y3eG5eD" crossorigin="anonymous"></script>
      <!-- <script src="https://code.jquery.com/jquery-3.6.4.slim.js" integrity="sha256-dWvV84T6BhzO4vG6gWhsWVKVoa4lVmLnpBOZh/CAHU4=" crossorigin="anonymous"></script> -->
      <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.6.4/jquery.js" integrity="sha512-6DC1eE3AWg1bgitkoaRM1lhY98PxbMIbhgYCGV107aZlyzzvaWCW1nJW2vDuYQm06hXrW0As6OGKcIaAVWnHJw==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>

</body>
</html>

templates/upload_form.html
<form method="post" enctype="multipart/form-data">
    <input type="file" name="files-input" id="" accept="image/jpeg" multiple>
    <button type="submit">Upload and Create Video</button>
</form>