pages/urls.py
from django.urls import path 
from . import views 
import pages 

app_name = 'pages' 

urlpatterns = [
    path('', views.index, name='index'), 
    path('check/', views.check_plan, name='check'), 
    path('contact/', views.contact_form, name='contact') 
]

pay/urls.py
from django.urls import path
from .views import plan_details , plans, create_subscription, videos_limit_end
from django.conf import settings
from django.conf.urls.static import static

app_name = "pay"




urlpatterns = [
    path("plans/", plans, name="plans"),
    path("plan_detalis/<int:id>", plan_details, name="plan_detalis"),
    path("create_subscription/", create_subscription, name='create-subscription'),
    path('limit_ended/', videos_limit_end, name='video_limit_end'), 
]

project/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static




urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('accounts/', include('users.urls', namespace='accounts')),
    path('', include('pages.urls', namespace='pages')),
    path('video/', include('video.urls',namespace='video')), 
    path('image/', include('image.urls', namespace='image')),
    path('audio/', include('audio.urls', namespace='audio')),
    path('pay/', include('pay.urls', namespace='pay')),
    path('video-v2/', include('video_v2.urls', namespace='video-v2')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)


handler404 = "pages.views.handler404"
handler500 = "pages.views.handler500"

pay/models.py
from django.db import models
from django.db import models
from django.contrib.auth.models import User
import datetime
# Create your models here.

class Plan(models.Model):
    name=models.CharField(max_length=100, verbose_name='اسم الباقة')
    price=models.IntegerField(verbose_name="سعر الباقة")
    validaity=models.CharField(max_length=100, verbose_name="دورة الباقة (30 يوم)")
    unlimited=models.BooleanField(default=False, verbose_name='غير محدودة')
    videos_per_months = models.IntegerField(default=0)
    
    def __str__(self):
        return self.name



class Subscription(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    plan = models.ForeignKey(Plan, on_delete=models.CASCADE)
    start_date = models.DateField(auto_now_add=True)
    end_date_time = models.DateField(blank=True, null=True)
    videos_per_months = models.IntegerField(default=0)

    # def save(self, *args, **kwargs ):
    #     if not self.end_date_time:
    #      # (or do something with `self.period`?)
    #         self.end_date_time = datetime.datetime.strptime(self.start_date, "%YYYY-%MM-%DD") + datetime.timedelta(days=int(self.plan.validaity))
    #     elif self.plan.unlimited == True:
    #         self.end_date_time = 9999-12-12

    #     super(Subscription, self).save(*args, **kwargs)
    
    
    def __str__(self):
        return f"{self.user.username}'s {self.plan.name} subscription"


class Feature(models.Model):
    plan =models.OneToOneField(Plan, on_delete=models.CASCADE)
    # numberVideos =models.IntegerField()
    template1 = models.BooleanField(default=True, verbose_name="النموذج الأول") 
    video_imgs_template = models.BooleanField(default=True, verbose_name="نموذج صور وفيديوهات")
    template2 = models.BooleanField(default=False, verbose_name="نموذج فيديو مع لوجو") 
    template3 = models.BooleanField(default=False, verbose_name="نموذج تقييم") 

    change_img_size = models.BooleanField(default=False, verbose_name="تغيير حجم الصور") 
    remove_audio = models.BooleanField(default=False, verbose_name="إزالة الصوت من الفيديو")
    change_video_speed = models.BooleanField(default=False, verbose_name="تغيير سرعة الفيديو") 
    change_audio_speed = models.BooleanField(default=False, verbose_name="تغيير سرعة الصوت") 

    watermark= models.BooleanField(default=True, verbose_name="العلامة المائية")

    def __str__(self):
        return f"{self.plan} Features"

class PayPal(models.Model):
    PAYPAL_CLIENT_ID = models.CharField(max_length=255, blank=True, null=True)
    PAYPAL_SECRET = models.CharField(max_length=255, blank=True, null=True)
    PAYPAL_ACCESS_TOKEN = models.TextField( blank=True, null=True)
    PAYPAL_CURRENCY = models.CharField(max_length=10, blank=True, null=True)
    
    class Meta:
        verbose_name = ('Paypal')
        verbose_name_plural = ('Paypals')

    

pay/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from .models import Plan,Feature,Subscription , PayPal
from django.contrib.auth.models import User 
import datetime
from django.views.decorators.csrf import csrf_exempt

# Create your views here.


# detail of plan


def videos_limit_end(request):
    return render(request, 'pay/videos_end.html', {})


def plans(request):
    plans = Plan.objects.all()
    feature_obj = Feature.objects.all()
    context={
        "plans":plans,
        "features": feature_obj,
    }
    return render (request, 'pay/plans.html', context) 


def plan_details(request, id):
    try:
        user = request.user 
    except:
        pass 

    try: 
        subscription = Subscription.objects.get(user=user)
        subscriped = "True"
    except:
        subscriped = "False"

    feature=Feature.objects.get(id=id)
    plans = Plan.objects.get(id=id)
    paypal_info = PayPal.objects.last()
    context={
        "plans":plans,
        "feature": feature,
        "paypal_info":paypal_info,
        "subscriped": subscriped,
    }
 
    return render (request, 'pay/plan_details.html' , context) 


@csrf_exempt
def create_subscription(request): 
    if request.method == 'POST':
        # Values 
        #user , plan, start-date 

        user = request.POST.get ('user') 
        plan = request.POST.get('plan') 

        start_date = request.POST.get('start-date') 

        selected_plan = Plan.objects.get(name=plan)
        
        user_object = User.objects.get(username=user)
        
        start_date = datetime.datetime.strptime(start_date, '%d-%m-%Y')

        if selected_plan.unlimited == True: 
            end_date_time = start_date + datetime.timedelta(days=int(100000))
        else:
            end_date_time = start_date + datetime.timedelta(days=int(selected_plan.validaity))


        Subscription.objects.create(user=user_object, start_date=start_date, plan=selected_plan, end_date_time=end_date_time, videos_per_months=selected_plan.videos_per_months)
        return redirect('/') 
        

    return render(request, 'pages/checking.html')

pay/templates/pay/plan_details.html
{% extends 'base.html' %}

{% block title %}
{{plans}}
{% endblock title %}

{%  block content  %}

<div class="container mt-5">
      <div class="row ">
          <div class="card">
            <!-- <div class="card-header mt-4 form-control"> -->
              <h3 class="card-title mt-3">{{plans.name}} 🔥🔥</h3>
            <!-- </div> -->
            <div class="card-body">
                  <h5 class="card-text"><b>{{plans.price}} $</b> / شهرياً</h5>
                  <br>
                  <h5 class="card-text">{{feature.videoTemplates}} نموذج فيديو</h5>
                  <br>

                  <h5 class="card-text">
                    {% if feature.watermark == 0 %}

                    <p>
                      <i class="fa-regular fa-circle-check" style="color: #008040;"></i>
                       بدون علامة مائية 
                    </p>
  
                    {% else %}
                    <p>
                      <i class="fa-regular fa-circle-xmark" style="color: #ff0000;"></i>
                       بدون علامة مائية
                    </p>
                    {% endif %}
                  </h5>
                  <!-- تبقى هنا التحقق من أن الباقة مجانية أو لا -->
	          {% if not subscriped == "True" %}
                  {% if plans.price == 0 %}
                    <a href="#" id="subscribe_button" class="btn btn-lg btn-dark form-control mb-3">اشترك في الباقة</a>
                  {% else %}

                <a href="{% url 'pages:contact' %}" class="btn btn-lg btn-dark form-control mb-3">تواصل مع الدعم</a>
                <div id="smart-button-container">
                  <div style="text-align: center">
                    <div id="paypal-button-container"></div>
                  </div>
              </div>
              {% endif %}
              {% endif %}

            </div>
          </div>
        

        <!-- Include the PayPal JavaScript SDK -->
        <!-- <script src="https://www.paypal.com/sdk/js?client-id={{paypal_info.PAYPAL_CLIENT_ID}}&currency={{paypal_info.PAYPAL_CURRENCY }}" data-namespace="paypal_sdk"></script> -->

        <!-- <script src="https://www.paypal.com/sdk/js?client-id={{paypal_info.PAYPAL_CLIENT_ID}}&currency={{paypal_info.PAYPAL_CURRENCY}}" data-sdk-integration-source="button-factory" data-namespace="paypal_sdk"></script>​ -->
        <!-- <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script> -->

        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.6.4/jquery.js" integrity="sha512-6DC1eE3AWg1bgitkoaRM1lhY98PxbMIbhgYCGV107aZlyzzvaWCW1nJW2vDuYQm06hXrW0As6OGKcIaAVWnHJw==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>

        <script>

          


          let subscribeButton = document.querySelector('#subscribe_button')

          $(subscribeButton).click(function () {

            
            const date = new Date(); 

            let day = date.getDate(); 
            let month = date.getMonth() + 1
            let year = date.getFullYear() 


            // Send Ajax Request 
            $.ajax({
              url: "{% url 'pay:create-subscription' %}", 
              type: "POST",
              data: {
                'user': "{{user}}", 
                'plan': "{{plans}}",
                'start-date': `${day}-${month}-${year}`
              },   
              success: function(response) {
                

              }, error: function(xhr, status, error) {
                console.log(error);
              }
            })
            
          } )



            


        </script>
        {% if not plans.price == 0 %}
        <script src="https://www.paypal.com/sdk/js?client-id={{paypal_info.PAYPAL_CLIENT_ID}}" data-namespace="paypal_sdk"></script>
        <script>
          
          function initPayPalButton() {
            paypal_sdk.Buttons({
                style: {
                  shape: "rect",
                  color: "gold",
                  layout: "vertical",
                  label: "paypal",
                },
                createOrder: function (data, actions) {
                  return actions.order.create({
                    purchase_units: [
                      {
                        amount: {
                          currency_code: "USD",

                          value: "{{plans.price}}",
                        },
                      },
                    ],
                  });
                },
                onApprove: function (data, actions) {
                  return actions.order.capture().then(function (orderData) {
                    // Full available details
                    console.log(
                      "Capture result",
                      orderData,
                      JSON.stringify(orderData, null, 2)
                    );

                    // Show a success message within this page, e.g.


                    const date = new Date(); 

                    let day = date.getDate(); 
                    let month = date.getMonth() + 1
                    let year = date.getFullYear() 


                    // Send Ajax Request 
                    $.ajax({
                      url: "{% url 'pay:create-subscription' %}", 
                      type: "POST",
                      data: {
                        'user': "{{user}}", 
                        'plan': "{{plans}}",
                        'start-date': `${day}-${month}-${year}`
                      },  success: function(response) {
                        console.log(response);
                        const element = document.getElementById(
                          "paypal-button-container"
                        );
                        element.innerHTML = "";
                        element.innerHTML = "<h3>تم تفعيل اشتراكك</h3>";
                      }, error: function(xhr, status, error) {
                        console.log(error);
                      }
                    })




                    // Or go to another URL:  actions.redirect('thank_you.html');
                  });
                },

                onError: function (err) {
                  console.log(err);
                },
              })
              .render("#paypal-button-container");
          }
          initPayPalButton();
        </script>
        {% endif %}


      </div>
    </div>


{%  endblock content  %}

pay/templates/pay/plans.html
{% extends 'base.html'  %}

{% block title %}
الأسعار
{% endblock %}


{% block content %}

    <style>
      * {
        font-family: 'Cairo', sans-serif;
      }
      .head{
        text-align: center;
            font-family: unset;
    font-weight: 600;
    color: #84848d;
      }
      .card{
        border: .5px solid #84848d;
        border-radius: 3px;
        text-align: center;
      }
    </style>



   <div class="container head mt-5">
    <div class="row">
      <h1> الباقات </h1>
      </p>
    </div>
   </div>
  <div class="container mt-5">
    <div class="row">  

     
       {% for p  in plans  %}  

      <div class="col-lg-4 col-md-6 col-sm-12">
        <div class="card shadow-lg mb-5 bg-white">
          <div class="card-header">
            <h5 class="card-title">{{p.name}}</h5>
          </div>
          <div class="card-body"> 
            <h2 class="card-text">{{p.price}} $ / شهرياً</h2>
            
              {% for feature in features %}
                {% if feature.plan.name == p.name %}
                  <p class="card-text">{{feature.plan.videos_per_months}} فيديوهات </p>  

                  {% if feature.watermark == 0 %}

                  <p>
                    <i class="fa-regular fa-circle-check" style="color: #008040;"></i>
                     بدون علامة مائية 
                  </p>

                  {% else %}
                  <p>
                    <i class="fa-regular fa-circle-xmark" style="color: #ff0000;"></i>
                     بدون علامة مائية
                  </p>
                  {% endif %}

		{% if feature.template1 == 0 %}
		<p>
		<i class='fa-regular fa-circle-check' style='color: #ff0000'  > نموذج فيديو عادي </i>
		</p>
		{% else %}
                <p>
                <i class='fa-regular fa-circle-check' style='color: #008040' > نموذج فيديو عادي</i>
                </p>
		{% endif %}



                {% if feature.template2 == 0 %}
                <p>
                <i class='fa-regular fa-circle-check' style='color: #ff0000' > نموذج فيديو مع لوجو</i>
                </p>
                {% else %}
                <p>
                <i class='fa-regular fa-circle-check' style='color: #008040' > نموذج فيديو مع لوجو</i>
                </p>
                {% endif %}



                {% if feature.template3 == 0 %}
                <p>
                <i class='fa-regular fa-circle-check' style='color: #ff0000' > نموذج فيديو تقييم</i>
                </p>
                {% else %}
                <p>
                <i class='fa-regular fa-circle-check' style='color: #008040' > نموذج فيديو تقييم</i>
                </p>
                {% endif %}


                {% if feature.change_img_size == 0 %}
                <p>
                <i class='fa-regular fa-circle-check' style='color: #ff0000' > تغيير حجم الصور</i>
                </p>
                {% else %}
                <p>
                <i class='fa-regular fa-circle-check' style='color: #008040' > تغيير حجم الصور</i>
                </p>
                {% endif %}


                {% if feature.remove_audio == 0 %}
                <p>
                <i class='fa-regular fa-circle-check' style='color: #ff0000' > إزالة الصوت من الفيديو</i>
                </p>
                {% else %}
                <p>
                <i class='fa-regular fa-circle-check' style='color: #008040' > إزالة الصوت من الفيديو</i>
                </p>
                {% endif %}



                {% if feature.change_video_speed == 0 %}
                <p>
                <i class='fa-regular fa-circle-check' style='color: #ff0000' > تغيير سرعة الفيديو</i>
                </p>
                {% else %}
                <p>
                <i class='fa-regular fa-circle-check' style='color: #008040' > تغيير سرعة الفيديو</i>
                </p>
                {% endif %}


                {% if feature.change_audio_speed == 0 %}
                <p>
                <i class='fa-regular fa-circle-check' style='color: #ff0000' > تغيير سرعة الصوت</i>
                </p>
                {% else %}
                <p>
                <i class='fa-regular fa-circle-check' style='color: #008040' > تغيير سرعة الصوت</i>
                </p>
                {% endif %}


                {% endif %}
              {% endfor  %}
              
                  
            <a class="btn btn-dark form-control" href="{% url 'pay:plan_detalis' p.id %}">تفاصيل</a>
          </div>
        </div>
      </div>
  {% endfor %}


{% endblock content %}

pay/templates/pay/videos_end.html
{% extends 'base.html' %}

{% block title %}
رسالة تنبيه
{% endblock title %}


{% block content %}


<style>
    .container {
        min-height: calc(100vh - 100px);
        display:flex !important; 
        justify-content: center;
        align-items: center;
    }
    h1:first-of-type {
        font-size: 100px; 
    }
</style>

<center>
    <h2>لقد تجاوزت العدد المسموح به من الفيديوهات شهرياً</h2>
    
    <a href="{% url 'pay:plans' %}" class="btn btn-dark">تجديد الباقة</a>
</center>

{% endblock content %}